llm: gemini
model: gemini-2.5-flash
toolsets:
  - name: read_only
    tools:
      - read_file
      # - read_repo # Not implemented yet
  - name: default # Special toolset that gets loaded when no other toolset is specified
    tools:
      - read_file
      - write_file
      - execute_command
      - mcp-sqlite.list_tables
      - mcp-sqlite.query
      # - google-pse-mcp.search # Example for a not-yet-implemented MCP tool

# List of additional servers (e.g., for external tools like web search)
additional_mcp_servers:
  # - name: google-pse-mcp
  #   command: npx
  #   args:
  #     - -y
  #     - google-pse-mcp
  #     - https://www.googleapis.com/customsearch
  #     - <api_key>
  #     - <cx>
  # Test with inspector:
  # npx -y @modelcontextprotocol/inspector npx -y mcp-sqlite test.db
  - name: mcp-sqlite
    command: npx
    args:
      - -y
      - mcp-sqlite
      - test.db

# Allowed OS commands
allowed_commands:
  - whoami
  - ls -la
  - "git .*" # Allow all git commands via regex
  - "go test ./..."

# Filesystem access rules
filesystem_access:
  hidden:
    - "**/.git/**"
    - "**/node_modules/**"
    - "secret.txt"
  read_only:
    - "go.mod"
    - "README.md"
