llm: gemini
model: gemini-2.5-flash
# llm: openai
# model: gpt-5-mini
toolsets:
  - name: read_only
    tools:
      - read_file
  - name: default # Special toolset that gets loaded when no other toolset is specified
    tools:
      - read_dir
      - read_file
      - write_file
      - execute_command
      - mcp-sqlite.list_tables
      - mcp-sqlite.query
      - gopls.go_workspace
      - gopls.go_package_api
      - gopls.go_diagnostics
      # - google-pse-mcp.search # Example for a not-yet-implemented MCP tool

# List of additional servers (e.g., for external tools like web search)
additional_mcp_servers:
  # - name: google-pse-mcp
  #   command: npx
  #   args:
  #     - -y
  #     - google-pse-mcp
  #     - https://www.googleapis.com/customsearch
  #     - <api_key>
  #     - <cx>
  # Test with inspector:
  # npx -y @modelcontextprotocol/inspector npx -y mcp-sqlite test.db
  - name: mcp-sqlite
    command: npx
    args:
      - -y
      - mcp-sqlite
      - test.db
  # go install go install golang.org/x/tools/gopls@latest
  - name: gopls
    command: gopls
    args:
      - mcp

# Allowed OS commands
allowed_commands:
  - whoami
  - ls -la
  - "git .*" # Allow all git commands via regex
  - "go test ./..."

# Filesystem access rules
filesystem_access:
  hidden:
    - "**/.git/**"
    - "**/node_modules/**"
    - "secret.txt"
    - ".compell/sessions/**"
    - "bin/**"
  read_only:
    - "go.mod"
    - "REQUIREMENTS.md"
    - "LICENSE"
